name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "https://video-cart-dev.vercel.app/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = " npm exec react-router dev"
